### ISSUE TITLE
Refresh tokens

### ISSUE THREAD

**Issue by zaksnet** [FastEndpoints/FastEndpoints#368] opened 2023-01-28 08:21 UTC
Shouldn't those be serialized and sent to the client? Otherwise how will the client know when to update the token:
```CSharp
[JsonIgnore] public DateTime AccessExpiry { get; internal set; }

[JsonIgnore] public DateTime RefreshExpiry { get; internal set; }
```

~~Also, woudn't it be better if DateTime was DateTimeOffset?~~

EDIT: Also, once i use the refresh token to get a new access token the new token does not seem to contain the claims. As far as i can tell everything has been set up properly inside `SetRenewalPrivilegesAsync` method.
EDIT: After some testing it seems that the priviledges are only not working if you await something within `SetRenewalPrivilegesAsync`

**Comment by dj-nitehawk** [comment] 2023-01-28 12:22
following is the line of thinking behind this choice:

90% of the time, developers would be subclassing the `TokenResponse` class and adding their own properties to it. different front-end clients expect the date strings to be in different formats/locals. so it makes sense to not serialize the `DateTime` properties and allow the developer to add a calculated property for the purpose of serialization of date/time strings.

the balance 10% of the time, the front-end application is fully aware of the expiration time of tokens and takes steps to automatically acquire new tokens way before they expire. so it's not necessary to send back the validity/expiry times in the response.

> the priviledges are only not working if you await something within `SetRenewalPrivilegesAsync`
i can look in to that if you can send a self contained repro. last i checked, everything was working as intended. could just be an async/await issue in your code.

**Comment by zaksnet** [comment] 2023-01-28 13:04
[Refresh-Tokens-Demo.zip](https://github.com/FastEndpoints/FastEndpoints/fi'les/10527284/Refresh-Tokens-Demo.zip)

> i can look in to that if you can send a self contained repro. last i checked, everything was working as intended. could just be an async/await issue in your code.

There you go:
Decoded JWT after login:
![image](https://user-images.githubusercontent.com/1850856/215267688-0422cf9d-a3ce-4971-8107-f2e1cfbb9824.png)
Decoded JWT after Refresh:
![image](https://user-images.githubusercontent.com/1850856/215267759-3c793953-602a-4e4b-a52d-ab22dc63fc87.png)

If you remove `await Task.Delay(3)` then it will properly populate the claims, otherwise (after debugging the code) `SetRenewalPrivilegesAsync` seems to be running after CreateToken has finished for some reason.

**Comment by zaksnet** [comment] 2023-01-28 13:06
The attached file is your demo project of Refresh tokens with in memory persistence

**Comment by zaksnet** [comment] 2023-01-28 13:07
> 90% of the time, developers would be subclassing the TokenResponse class and adding their own properties to it. different front-end clients expect the date strings to be in different formats/locals. so it makes sense to not serialize the DateTime properties and allow the developer to add a calculated property for the purpose of serialization of date/time strings.

the balance 10% of the time, the front-end application is fully aware of the expiration time of tokens and takes steps to automatically acquire new tokens way before they expire. so it's not necessary to send back the validity/expiry times in the response.

I understand.

**Comment by dj-nitehawk** [comment] 2023-01-28 16:48
thanks for the repro...
it was a nasty bug which is now fixed in `v5.6.0.6-beta`
thanks for reporting...

**Closed by dj-nitehawk** 2023-01-28 16:48 UTC
Labels: bug, fixed

**Comment by zaksnet** [comment] 2023-01-28 17:08
> thanks for the repro...
> it was a nasty bug which is now fixed in v5.6.0.6-beta
> thanks for reporting...

Thanks for the fast resolution. I just tested this with `v5.6.0.6-beta` and i see the same behavior though (i have tried cleaning the project).

 Also, i might be missing something here but after the token is refreshed you automatically return a response that does not include the expiration dates. So basically i have derived from TokenResponse and added these fields:
```CSharp
public DateTimeOffset RefreshExpiryTime { get; set; }
public DateTimeOffset AccessExpiryTime { get; set; }
```

But i'm not sure how to populate them when the token is refreshed. It works on creation because i return the response. I have also tried populating the `Response` inside of `PersistTokenAsync` but that didnt help.

**Comment by dj-nitehawk** [comment] 2023-01-29 03:43
[Refresh-Tokens-Demo.zip](https://github.com/FastEndpoints/FastEndpoints/files/10528895/Refresh-Tokens-Demo.zip)

check out this updated project. it's simply a matter of adding a getter only (calculated) property to your derived class, which just transforms the datetime to whatever format the front-end client is capable of handling.

**Comment by dj-nitehawk** [comment] 2023-01-29 04:27
also updated the repo:
https://github.com/FastEndpoints/Refresh-Tokens-Demo/blob/a49406f2ea694ff9d759cf2a54ae612e8533290b/Features/User/Auth/MyTokenResponse.cs#L3-L12

**Comment by zaksnet** [comment] 2023-01-29 05:52
Thank you!
