### ISSUE TITLE
PATCH with route param, headers and no body

### ISSUE THREAD

**Issue by Pt4r** [FastEndpoints/FastEndpoints#801] opened 2024-10-17 08:09 UTC
What im trying to do is send a PATCH call to an endpoint which has route params but also required headers and no body. This should not send a body or a Content-type header.

```csharp
public class TestRequest
{
    [FromHeader("x-correlation-id")]
    public Guid CorrelationId { get; set; }
    [BindFrom("EntityId")]
    public Guid EntityId { get; set; }
}
```

```csharp
public sealed class TestEndpoint : Endpoint<TestRequest>
{
    public override void Configure()
    {
        Patch("{EntityId}/fulfill");
    }

    public override async Task HandleAsync(TestRequest req, CancellationToken cancellationToken)
    {
        await SendOkAsync(cancellationToken);
    }
}
```

The above displays the 2 properties in Swagger UI but when i call it i get 415 Unsupported Media Type which as i understand is returned because the FastEndpoints `Endpoint<T>` sends a body even though its empty. I can verify this if i manually send the properties as the route param and header accordingly and set the `Content-type: application/json` header which in turn returns a JsonSerializer error because the body is null and not in a json format.

I have also tried with `EndpointWithoutRequest` but this does not take any model as a request therefore the `CorrelationId` prop cannot be set through Swagger UI.

What i would like to find is a way to display all the header properties and the route params in SwaggerUI and be able to send a simple curl with 
```
curl -X 'PATCH' \
  '.../72423509-c29b-4735-862a-9ebdd0489c05/fulfill' \
  -H 'x-correlation-id: 72423509-c29b-4735-862a-9ebdd0489c05'
```

**Comment by dj-nitehawk** [comment] 2024-10-17 08:12
i believe this is a duplicate of https://github.com/FastEndpoints/FastEndpoints/issues/492#issuecomment-1740210893
if not, feel free to reopen and i'll have a deeper look.
thanks!

**Closed by dj-nitehawk** 2024-10-17 08:12 UTC
