### ISSUE TITLE
Source generator fails in v5.31

### ISSUE THREAD

**Issue by jbrezina** [FastEndpoints/FastEndpoints#837] opened 2024-11-25 20:09 UTC
I have an endpoint similar to the following code:
```csharp
using SlackNet;
using SlackNet.WebApi;

namespace MyNamespace;

internal sealed record MyRequest(Message Message);

internal class MyEndpoint(...) : Endpoint<MyRequest>
```

I use FastEndpoints.Generator in my library containing the endpoint. Build ends with the following errors:
```
Error CS0144 Cannot create an instance of the abstract type or interface 'Block'
FastEndpoints.Generator\FastEndpoints.Generator.ReflectionGenerator\ReflectionData.g.cs
Error CS0144 Cannot create an instance of the abstract type or interface 'ActionElement'
FastEndpoints.Generator\FastEndpoints.Generator.ReflectionGenerator\ReflectionData.g.cs
```
Message, Block and ActionElement are classes contained within SlackNet library. Block and ActionElement are abstract.
The code worked just fine in the previous version (v5.30).

When I change the request from record to class, the build is successful.
```csharp
internal sealed class MyRequest(Message message)
{
	public Message Message { get; } = message;
}
```

May be related to [Polymorphism issue in ReflectionGenerator #813](https://github.com/FastEndpoints/FastEndpoints/issues/813)

**Comment by dj-nitehawk** [comment] 2024-11-26 03:04
i believe this has been fixed already. please try the latest beta version from nuget and report back if it's still reproducible.
thanks!

**Comment by jbrezina** [comment] 2024-11-26 06:52
I still have a problem with the v5.31.0.18-beta. In another endpoint I use SendGrid v9.29.3 library. The SendGridMessage is within SendGrid.Helpers.Mail namespace.

```csharp
using SendGrid;
using SendGrid.Helpers.Mail;

namespace MyNamespace;

internal sealed record MyRequest(SendGridMessage Message);

internal class MyEndpoint() : Endpoint<MyRequest>
```

Build fails with the following error message
```
Error CS0234 The type or namespace name 'Helpers' does not exist in the namespace 'MyNamespace' (are you missing an assembly reference?)
FastEndpoints.Generator\FastEndpoints.Generator.ReflectionGenerator\ReflectionData.g.cs
```

**Comment by AMW93** [comment] 2024-11-26 16:11
Same problem on my end

**Comment by dj-nitehawk** [comment] 2024-11-27 05:07
tried to replicate the issue but seems to be working fine. i get the following generated content. also i wouldn't personally expose a heavy model like that to the outside world. best to use a limited dto and map to a `SendGridMessage` yourself. will close this issue until someone provides a repro project to check. thanks!

![screen-record-1732683964](https://github.com/user-attachments/assets/154ed672-397c-4348-af76-56b4086cfcf2)

**Closed by dj-nitehawk** 2024-11-27 05:07 UTC
Labels: pending investigation
