### ISSUE TITLE
Not able to use it with latest EF, Serilog and Microsoft.Extensions.DependencyInjection.Abstractions

### ISSUE THREAD

**Issue by moedeveloper** [FastEndpoints/FastEndpoints#542] opened 2023-11-22 10:57 UTC
I am not able to use this package with the :
Microsoft.Extensions.DependencyInjection.Abstractions 
EF
Serlig 

latest version, I am getting the following conflict.

Remember I am using dotnet 8

Error | NU1107 | Version conflict detected for Microsoft.Extensions.DependencyInjection.Abstractions. Install/reference Microsoft.Extensions.DependencyInjection.Abstractions 8.0.0 directly to project Khotabaa.WebAPI to resolve this issue.  Khotabaa.WebAPI -> Khotabaa.Persistence -> Microsoft.EntityFrameworkCore 8.0.0 -> Microsoft.Extensions.Logging 8.0.0 -> Microsoft.Extensions.Options 8.0.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 8.0.0)  Khotabaa.WebAPI -> FastEndpoints.Swagger 5.19.2 -> NSwag.AspNetCore 13.20.0 -> NSwag.Generation.AspNetCore 13.20.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 7.0.0 && < 8.0.0). | Khotabaa.WebAPI | C:\Users\Administrator\Desktop\khotabaa-poem\src\WebAPI\Khotabaa.WebAPI.csproj | 1 |

**Comment by dj-nitehawk** [comment] 2023-11-22 11:25
looks like a duplicate of #541

**Closed by dj-nitehawk** 2023-11-22 11:25 UTC
